package web.locators;

import org.openqa.selenium.By;

public class CompanyPageLocators {
    public static final String TABS = "//ul[@id='tabs']//li[@data_id=\"%s\"]";
    public static final String VALIDATION_POPUP_HEADER = "//div//header[text()=\"%s\"]";
    public static final String VALIDATION_MESSAGE = "//div[contains(@id, 'jalert_')]//div//span[@class='content' and text()=' %s']";
    public static final String VALIDATION_MESSAGE2 = "//div[contains(@id, 'jalert_')]//div//span[@class='content' and text()=\"%s\"]";
    public static final String TABLE_OF_SHORT_NAME = "//td[@name='short_name' and @title=\"%s\"]";
    public static final String ADD_BUTTON_INSIDE_COMPANY = "//div[@id=\"%s\"]/../../../../../../../tr/td/table/tbody/tr/td/a/img";
    public static final String ADD_BUTTON_INSIDE_DESIGNATION_OF_COMPANY = "//div[@id=\"%s\"]/../../../../../../../tr/td/table/tbody/tr/td/a/img[@id=\"overviewpopuplink\"]";
    public static final String EXPENSE_CLAIMABLE_CHECKBOX = "//input[@id='is_claimable0_1']";
    public static final By SHIFT_VALID_FROM = By.xpath("//input[@id='-validfrom']");
    public static final By SHIFT_VALID_TO = By.xpath("//input[@id='-validto']");
    public static final String FLEXIBLE_SHIFT = "//input[@id='shift_type_2']";
    public static final String USER_STATUS_ACTIVE = "//input[@id='use_active_1']";
    public static final String USER_STATUS_INACTIVE = "//input[@id='use_active_2']";
    public static final String SHOW_DEFAULT_FIlTER_OPTION_IS_ON = "//input[@id='show_default_filter_option_1']";
    public static final String SHOW_DEFAULT_FIlTER_OPTION_IS_OFF = "//input[@id='show_default_filter_option_2']";
    public static final String WEB_NOTIFICATION_CHECKBOX = "(//input[@id='notification_1'])[1]";
    public static final String WEB_ACCESS_NONE = "//input[@id='web_access_2']";
    public static final String WEB_ACCESS_ALL = "//input[@id='web_access_1']";
    public static final String MOBILE_ACCESS_NONE = "//input[@id='mobile_access_2']";
    public static final String MOBILE_ACCESS_ALL = "//input[@id='mobile_access_1']";
    public static final String ADDRESS_FROM_MAP_PROVIDER_CHECKBOX = "//input[@id='address_from_map0_1']";
    public static final String DEFAULT_MAP_CHECKBOX = "//input[@id='default_map0_1']";
   
    public static final By COMPANY_DETAILS_COUNTRY_DROPDOWN = By.xpath("//div[@id='country_chosen']");
    public static final String COMPANY_DETAILS_COUNTRY_DROPDOWN_OPTION = "//div[@id='country_chosen']//div[@class='chosen-drop']//ul//li[@title=\"%s\"]";
    public static final By COMPANY_DETAILS_STATE_DROPDOWN = By.xpath("//div[@id='state_chosen']");
    public static final String COMPANY_DETAILS_STATE_DROPDOWN_OPTION = "//div[@id='state_chosen']//div[@class='chosen-drop']//ul//li[@title=\"%s\"]";
    public static final By TIMEZONE_DROPDOWN = By.xpath("//div[@id='chosen30_container']");
    public static final String TIMEZONE_DROPDOWN_OPTION = "//div[@id='chosen30_container']//div[@class='chosen-drop']//ul//li[@title=\"%s\"]";
    public static final By DATE_FORMAT_DROPDOWN = By.xpath("//select[@name='date_format']");
    public static final String DATE_FORMAT_DROPDOWN_OPTION = "//select[@name='date_format']/option[text()=\"%s\"]";
    public static final By TIME_FORMAT_DROPDOWN = By.xpath("//select[@name='time_format']");
    public static final String TIME_FORMAT_DROPDOWN_OPTION = "//select[@name='time_format']/option[text()=\"%s\"]";
    public static final By UNITS_OF_DISTANCE_DROPDOWN = By.xpath("//select[@name='vehicle_output_scaling']");
    public static final String UNITS_OF_DISTANCE_DROPDOWN_OPTION = "//select[@name='vehicle_output_scaling']/option[text()=\"%s\"]";
    public static final By LANGUAGE_DROPDOWN = By.xpath("//div[@id='languagecode_chosen']");
    public static final String LANGUAGE_DROPDOWN_OPTION = "//div[@id='languagecode_chosen']//div[@class='chosen-drop']//ul//li[@title=\"%s\"]";
    public static final By MAP_DROPDOWN = By.xpath("//select[@name='geomap_id0']");
    public static final String MAP_DROPDOWN_OPTION = "//td[@id='geomap_id00']//select[@name='geomap_id0']//*[contains(text(),\"%s\")]";
    public static final By SOS_CATEGORY_DROPDOWN = By.xpath("//select[@name='category_type_id0']");
    public static final String SOS_CATEGORY_DROPDOWN_OPTION = "//td[@id='category_type_id00']//select[@name='category_type_id0']//*[contains(text(),\"%s\")]";
    public static By ADD_BUTTON = By.xpath("//a[@title='New']"); 
    public static By SAVE_BUTTON = By.xpath("//a[@title='Save']");
    public static By SHORT_NAME_FIELD = By.xpath("//input[@id='-short_name']");
    public static By USERNAME_FIELD = By.xpath("//input[@id='-username']");
    public static By CONFIRM_USERNAME_FIELD = By.xpath("//input[@id='-confirm_username']");
    public static By PASSWORD_FIELD = By.xpath("//input[@id=\"-password_val\"]");
    public static By RETYPE_PASSWORD_FIELD = By.xpath("//input[@id='-retype_password']");
    public static final String TWO_STEP_AUTHENTICATION_CHECKBOX = "//input[@id='two_step_authentication_1']";
    public static final String PASSWORD_RECOVERY_EMAIL = "//input[@id=\"-password_recovery_email\"]";
    public static final String ADD_GEOLOCATION = "//img[@id=\"add_geolocation\"]";
    public static final String GEOCODE_INPUT_FIELD = "//input[@id=\'geocoder_input\']";
    public static final String GEOCODE_SAVE_BUTTON = "//input[@id=\"btn_save\"]";
    public static By TELEPHONE_FIELD = By.xpath("//input[@id='-tel_no']");
    public static By MOBILE_NUMBER_FIELD = By.xpath("//input[@id='-mob_no']");
    public static By CITY_FIELD = By.xpath("//input[@id='-city']");
    public static By ZIP_CODE_FIELD = By.xpath("//input[@id='-zipcode']");
    public static By STREET1_FIELD = By.xpath("//input[@id='-street1']");
    public static By STREET2_FIELD = By.xpath("//input[@id='-Street2']");
    public static By CONTACT_PERSON_FIELD = By.xpath("//input[@id='-contact_person']");
    public static By FAX_NUMBER_FIELD = By.xpath("//input[@id='-fax_no']");
    public static By VATIN_NUMBER_FIELD = By.xpath("//input[@id='-vatin_no']");
    public static By CLOSE_BUTTON_OF_POPUP = By.xpath("//div/span[@class='jclosebtn' and text()='Close']");
    public static By DELETE_BUTTON = By.xpath("//a[@title='Delete']");
    public static By RULE_NAME_FIELD = By.xpath("//input[@id='-rule_name']");
    public static By SAVE_BUTTON_OF_DIALOG_BOX = By.xpath("//span[@value='Save']");
    public static By DEPARTMENT_NAME_FIELD = By.xpath("//input[@id='-department_name_i']");
    public static By DESIGNATION_NAME_FIELD = By.xpath("//input[@id='-designation_name']");
    public static By DEPARTMENT_DESCRIPTION_FIELD = By.xpath("//textarea[@id='-description_i']");
    public static By TASK_CATEGORY_NAME_FIELD = By.xpath("//input[@id='-task_category_name_i']");
    public static By TASK_DESCRIPTION_FIELD = By.xpath("//textarea[@id='-description_i']");
    public static By EXPENSE_CATEGORY_NAME_FIELD = By.xpath("//input[@id='-task_expense_category_name_i']");
    public static By EXPENSE_DESCRIPTION_FIELD = By.xpath("//textarea[@id='-description_i']");
    public static By SHIFT_NAME_FIELD = By.xpath("//input[@id='-shift_name']");
    public static By EDIT_SHIFT = By.xpath("(//img[@id='editImageDarkMode'])[1]");
    public static By sCHOOL_REGISTRATION_NUMBER = By.xpath("//input[@id=\"-sb_registration_number\"]");
    public static By CHARGER_ALERT_OPTION = By.xpath("//option[@value='178']");
    public static By ALL_ALERT_OPTION = By.xpath("//option[normalize-space()='All']");
    public static By WEB_MAP_KEY_FIELD = By.xpath("//input[@id='-map_key']");
    public static By SOS_CATEGORY_TYPE_FIELD = By.xpath("//input[@id='-category_name']");
    public static By SOS_REASON_DESCRIPTION_FIELD = By.xpath("//textarea[@id='-leave_reason_description_i']");
    public static By LEAVE_REASON_FIELD = By.xpath("//input[@id='-leave_reason_i']");
    public static By MOBILE_MAP_KEY_FIELD = By.xpath("//input[@id='-mobile_map_key']");
    public static By FROM_EMAIL_ADDRESS_FIELD_IN_EMAIL_TAB = By.xpath("//input[@id='-email_address_alert']");
    public static By USERNAME_FIELD_IN_EMAIL_TAB = By.xpath("//input[@id='-email_username_alert']");
    public static By PASSWORD_FIELD_IN_EMAIL_TAB = By.xpath("//input[@id='-email_password_alert']");
    public static By HOST_FIELD_IN_EMAIL_TAB = By.xpath("//input[@id='-email_host_alert']");
    public static By OUTGOING_PORT_FIELD_IN_EMAIL_TAB = By.xpath("//input[@id='-email_outgoing_port_alert']");
    public static By TEST_CONFIGURATION_BUTTON_IN_EMAIL_TAB = By.xpath("//input[@id='validate_email_config_btn']");
    public static By EMAIL_VERIFICATION_FIELD_IN_EMAIL_TAB = By.xpath("//input[@id='verify_email_to']");
    public static By EMAIL_VERIFICATION_BUTTON_IN_EMAIL_TAB = By.xpath("//input[@name='check_config_button']");
    public static final By EVENT_DATE_FORMAT_DROPDOWN = By.xpath("//select[@name='event_date_format']");
    public static final String EVENT_DATE_FORMAT_DROPDOWN_OPTION = "//select[@name='event_date_format']//option[contains(text(),\"%s\")]";
    public static final String GENERIC_LABEL_XPATH = "//label[contains(text(),\"%s\")]";
    public static final String MAP_TAB_XPATH = "//tr//td//div[contains(text(),\"%s\")]";
    public static By CLOSE_BUTTON_OF_RULE_TAB = By.xpath("//div[@class='ui-dialog ui-widget ui-widget-content ui-corner-all ui-draggable ui-resizable']//span[@class='ui-icon ui-icon-closethick']");
    public static By school_Confirmation_Checkbox = By.xpath("//input[@id=\"school_check_box\"]");
    public static By school_confirmation_save_button = By.xpath("//div[@class=\'buttons-box-save\']//input[@id=\'save_button\']");
    public static final By RESELLER_DROPDOWN = By.xpath("//div[@id='reseller_entity_id_chosen']");
    public static final String RESELLER_DROPDOWN_OPTION = "//div[@id='reseller_entity_id_chosen']//div[@class='chosen-drop']//ul//li[@title=\"%s\"]";

}