package web.locators;

import org.openqa.selenium.By;

public class EmployeePageLocators {

    public static final By COMPANY_DROPDOWN = By.xpath("//div[@id='company_id_chosen']");
    public static final String COMPANY_DROPDOWN_OPTION = "//div[@id='company_id_chosen']//div[@class='chosen-drop']//ul//li[@title=\"%s\"]";
    public static final By BRANCH_DROPDOWN = By.xpath("//select[@name='location_id']");
    public static final String BRANCH_DROPDOWN_OPTION = "//select[@name='location_id']//option[contains(text(),\"%s\")]";
    public static final By DEPARTMENT_DROPDOWN = By.xpath("//div[@id='task_department_id_chosen']");
    public static final String DEPARTMENT_DROPDOWN_OPTION = "//div[@id='task_department_id_chosen']//div[@class='chosen-drop']//ul//li[@title=\"%s\"]";
    public static final By DESIGNATION_DROPDOWN = By.xpath("//div[@id='designation_id_chosen']");
    public static final String DESIGNATION_DROPDOWN_OPTION = "//div[@id='designation_id_chosen']//div[@class='chosen-drop']//ul//li[@title=\"%s\"]";
    public static final By PRIMARY_REPORTING_DROPDOWN = By.xpath("//div[@id='primary_reporting_chosen']");
    public static final String PRIMARY_REPORTING_DROPDOWN_OPTION = "//div[@id='primary_reporting_chosen']//div[@class='chosen-drop']//ul//li[@title=\"%s\"]";
    public static final By SECONDARY_REPORTING_DROPDOWN = By.xpath("//div[@id='secondary_reporting_chosen']");
    public static final String SECONDARY_REPORTING_DROPDOWN_OPTION = "//div[@id='secondary_reporting_chosen']//div[@class='chosen-drop']//ul//li[@title=\"%s\"]";
    public static final By LIVE_DATA_SYNC_INTERVAL_DROPDOWN = By.xpath("//select[@name='live_data_sync_interval']");
    public static final String LIVE_DATA_SYNC_INTERVAL_DROPDOWN_OPTION = "//select[@name='live_data_sync_interval']//option[contains(text(),\"%s\")]";
    public static final By GPS_ACCURACY_DROPDOWN = By.xpath("//div[@id='gps_accuracy_chosen']");
    public static final String GPS_ACCURACY_DROPDOWN_OPTION = "//div[@id='gps_accuracy_chosen']//div[@class='chosen-drop']//ul//li[@title=\"%s\"]";
    public static final By CUSTOMER_DROPDOWN = By.xpath("//div[@id='customer_ids_chosen']");
    public static final String CUSTOMER_DROPDOWN_OPTION = "//div[@id='customer_ids_chosen']//div[@class='chosen-drop']//ul//li[@title=\"%s\"]";
    public static final By ADDRESS_DROPDOWN = By.xpath("//div[@id='address_book_overview_chosen']");
    public static final String ADDRESS_DROPDOWN_OPTION = "//div[@id='address_book_overview_chosen']//div[@class='chosen-drop']//ul//li[@title=\"%s\"]";
    public static final By AUTHENTICATION_TYPE_DROPDOWN = By.xpath("//select[@name='authentication_type']");
    public static final String AUTHENTICATION_TYPE_DROPDOWN_OPTION = "//select[@name='authentication_type']//option[contains(text(),\"%s\")]";
    public static final By QR_SCAN_EVENT_DROPDOWN = By.xpath("//select[@name='qr_scan_event']");
    public static final String QR_SCAN_EVENT_DROPDOWN_OPTION = "//select[@name='qr_scan_event']//option[contains(text(),\"%s\")]";
    public static final By QR_VALIDATION_DROPDOWN = By.xpath("//div[@id='qr_validation_chosen']");
    public static final String QR_VALIDATION_DROPDOWN_OPTION = "//div[@id='qr_validation_chosen']//div[@class='chosen-drop']//ul//li[@title=\"%s\"]";
    public static final By LANGUAGE_DROPDOWN = By.xpath("//div[@id='languagecode_chosen']");
    public static final String LANGUAGE_DROPDOWN_OPTION = "//div[@id='languagecode_chosen']//div[@class='chosen-drop']//ul//li[@title=\"%s\"]";
    public static final String FEMALE_RADIO_BUTTON = "//input[@id='gender_2']";
    public static final String MALE_RADIO_BUTTON = "//input[@id='gender_1']";
    public static final String VERIFICATION_VIA_PASSWORD_RADIO_BUTTON = "//input[@id='verification_via_2']";
    public static final String VERIFICATION_VIA_OTP_RADIO_BUTTON = "//input[@id='verification_via_1']";
    public static final By TIMEZONE_DROPDOWN = By.xpath("//div[@id='input_timezone_chosen']");
    public static final String TIMEZONE_DROPDOWN_OPTION = "//div[@id='input_timezone_chosen']//div[@class='chosen-drop']//ul//li[@title=\"%s\"]";
    public static final By SPEED_DETECTION_DROPDOWN = By.xpath("//div[@id='accuracy_speed_chosen']");
    public static final String SPEED_DETECTION_DROPDOWN_OPTION = "//div[@id='accuracy_speed_chosen']//div[@class='chosen-drop']//ul//li[@title=\"%s\"]";
    public static final By SHIFT_DROPDOWN = By.xpath("//div[@id='search_device_chosen']");
    public static final String SHIFT_DROPDOWN_OPTION = "//div[@id='search_device_chosen']//div[@class='chosen-drop']//ul//li[@title=\"%s\"]";
    public static final String AUTO_TASK_RADIO_BUTTON = "//input[@id='task_start_1']";
    public static final String MANUAL_TASK_RADIO_BUTTON = "//input[@id='task_start_2']";
    public static final By COUNTRY_DROPDOWN = By.xpath("//div[@id='country_chosen']");
    public static final String COUNTRY_DROPDOWN_OPTION = "//div[@id='country_chosen']//div[@class='chosen-drop']//ul//li[@title=\"%s\"]";
    public static final By LEAVE_TYPE_DROPDOWN = By.xpath("//select[@name='leave_type0']");
    public static final String LEAVE_TYPE_DROPDOWN_OPTION = "//td[@id='leave_type00']//select[@name='leave_type0']//*[contains(text(),\"%s\")]";
    public static final By EDIT_LEAVE_TYPE_DROPDOWN = By.xpath("//select[@name='leave_type0']");
    public static final String AUTO_RENEWAL_CHECKBOX = "//input[@id='auto_renewal0_1']";
    public static final String EDIT_AUTO_RENEWAL_CHECKBOX = "//input[@id='auto_renewal0_1']";
    public static final By RENEWAL_FREQUENCY_DROPDOWN = By.xpath("//select[@name='renewal_frequency0']");
    public static final String RENEWAL_FREQUENCY_DROPDOWN_OPTION = "//td[@id='renewal_frequency00']//select[@name='renewal_frequency0']//option[contains(text(),\"%s\")]";
    public static final By EDIT_RENEWAL_FREQUENCY_DROPDOWN = By.xpath("//select[@name='renewal_frequency0']");
    public static final String CARRY_OVER_CHECKBOX = "//input[@id='carry_over0_1']";
    public static final String TABLE_OF_FIRST_NAME = "//td[@name='first_name' and @title=\"%s\"]";
    public static final String DOB_INPUT = "//input[@id='-date_of_birth']";
    public static final String OFF_DUTY_RESTRICTION_CHECKBOX = "//input[@id='off_duty_restriction_check_1']";
    public static final String TASK_REMINDER_CHECKBOX = "//input[@id='task_reminder_check_1']";
    public static final String QR_CODE_CHECKBOX = "//input[@id='scan_qr_code_1']";
    public static final String TASK_APPROVAL_CHECKBOX = "//input[@id='task_approval_1']";
    public static By NO_RECORDS_FOUND_LABEL = By.xpath("//td//b[contains(text(), 'No Records Found')]");
    public static By DEPARTMENT_NAME_FIELD = By.xpath("//input[@id='-department_name']");
    public static By FIRST_NAME_FIELD = By.xpath("//input[@id='-first_name']");
    public static By MIDDLE_NAME_FIELD = By.xpath("//input[@id='-middle_name']");
    public static By LAST_NAME_FIELD = By.xpath("//input[@id='-last_name']");
    public static By EMPLOYEE_NUMBER_FIELD = By.xpath("//input[@id='-employee_no']");
    public static By PASSWORD_FIELD = By.xpath("//input[@id='-password_val']");
    public static By RETYPE_PASSWORD_FIELD = By.xpath("//input[@id='-retype_password']");
    public static By EMAIL_ID_FIELD = By.xpath("//input[@id='-email']");
    public static By MEDICLAIM_NUMBER_FIELD = By.xpath("//input[@id='-hes_id']");
    public static By MOBILE_NUMBER_FIELD = By.xpath("//input[@id='-mobile_no']");
    public static By EMERGENCY_CONTACT_NUMBER_FIELD = By.xpath("//input[@id='-emergency_contact']");
    public static By STREET1_FIELD = By.xpath("//input[@id='-street1']");
    public static By STREET2_FIELD = By.xpath("//input[@id='-street2']");
    public static By CITY_FIELD = By.xpath("//input[@id='-city']");
    public static By ZIPCODE_FIELD = By.xpath("//input[@id='-zip_code']");
    public static By NO_OF_DAYS_FIELD = By.xpath("//td[@id='no_of_days0']//input[@id='-no_of_days']");
    public static By EDIT_NO_OF_DAYS_FIELD = By.xpath("//td[@id='no_of_days0']//input[@id='-no_of_days']");
    public static final By CLEAR_TOKEN_BUTTON = By.xpath("//table[@data_id='profile']//tr//td//label[contains(text(),'Clear Token')]");
    public static final By CLEAR_TOKEN_NO_BUTTON = By.xpath("//div//span[@class='jconfirmclosebtn' and text()='No']");
    public static final By SYNC_MOBILE_LOGS_BUTTON = By.xpath("//table[@data_id='profile']//tr//td//label[contains(text(),'Sync Mobile Logs')]");
    public static final By SYNC_MOBILE_LOGS_CANCEL_BUTTON = By.xpath("//div//span[@class='jconfirmclosebtn' and text()='Cancel']");
    public static final By OUTSIDE_TAP = By.xpath("//table[@data_id='access_rights']");
    public static final String GENERAL_TAB_FIELD = "//label[contains(text(),\"%s\")]";
    public static final String LEAVE_DOCUMENT_TAB_FIELD = "//tr//td//div[contains(text(),\"%s\")]";
}